kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: glasskube
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "watch", "list"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: glasskube
  namespace: default


---

apiVersion: v1
kind: Secret
metadata:
  name: glasskube
  namespace: default
  annotations:
    kubernetes.io/service-account.name: "glasskube"
type: kubernetes.io/service-account-token

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: glasskube
subjects:
- kind: ServiceAccount
  name: glasskube
  namespace: default
roleRef:
  kind: ClusterRole
  name: glasskube
  apiGroup: rbac.authorization.k8s.io

